import Header from "./Header";
import { Poppins } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const inter = Poppins({
  subsets: ["latin"],
  weight: ["100", "200"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <nav>
          <Header />
        </nav>
        {children}
      </body>
    </html>
  );
}
